#spring:
# data:
#   mongodb:
#     username: ${MONGO_USER}
#     password: ${MONGO_PASSWORD}
#     database: ${MONGO_DATABASE}
#     port: ${MONGO_PORT}
#     host: ${MONGO_HOST}
#server:
# port: 8081

spring:
 data:
   mongodb:
     database: NewsServiceDB
     port: 27017
     host: localhost
server:
 port: 8081